cleanUp:
  consistencyLevel: ONE
  performValidation: Y
  dryRun: Y
  retainRecentPrimaryKeyRow: N
  filterConditions:
    - tenantId: f3919be0-4a0c-49e7-b7a3-ac2628c01712
      query: ""
  keyspaces:
    - name: test
      tables:
        - data_by_date
