cleanUp:
  consistencyLevel: ONE
  performValidation: Y
  dryRun: Y
  retainRecentPrimaryKeyRow: N
  filterConditions:
    - tenantId: c488891e-dd45-4206-a1f9-29933cb55423
      query: ""
  keyspaces:
    - name: test
      tables:
        - data_by_date
